################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
EXECUTABLES := 
OBJS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Common/Src \
Core/Src/lv_demos/src/lv_demo_benchmark/assets \
Core/Src/lv_demos/src/lv_demo_benchmark \
Core/Src/lv_demos/src/lv_demo_keypad_encoder \
Core/Src/lv_demos/src/lv_demo_music/assets \
Core/Src/lv_demos/src/lv_demo_music \
Core/Src/lv_demos/src/lv_demo_stress/assets \
Core/Src/lv_demos/src/lv_demo_stress \
Core/Src/lv_demos/src/lv_demo_widgets/assets \
Core/Src/lv_demos/src/lv_demo_widgets \
Core/Src/lvgl/examples/anim \
Core/Src/lvgl/examples/assets \
Core/Src/lvgl/examples/event \
Core/Src/lvgl/examples/get_started \
Core/Src/lvgl/examples/layouts/flex \
Core/Src/lvgl/examples/layouts/grid \
Core/Src/lvgl/examples/others/snapshot \
Core/Src/lvgl/examples/porting \
Core/Src/lvgl/examples/scroll \
Core/Src/lvgl/examples/styles \
Core/Src/lvgl/examples/widgets/animimg \
Core/Src/lvgl/examples/widgets/arc \
Core/Src/lvgl/examples/widgets/bar \
Core/Src/lvgl/examples/widgets/btn \
Core/Src/lvgl/examples/widgets/btnmatrix \
Core/Src/lvgl/examples/widgets/calendar \
Core/Src/lvgl/examples/widgets/canvas \
Core/Src/lvgl/examples/widgets/chart \
Core/Src/lvgl/examples/widgets/checkbox \
Core/Src/lvgl/examples/widgets/colorwheel \
Core/Src/lvgl/examples/widgets/dropdown \
Core/Src/lvgl/examples/widgets/img \
Core/Src/lvgl/examples/widgets/imgbtn \
Core/Src/lvgl/examples/widgets/keyboard \
Core/Src/lvgl/examples/widgets/label \
Core/Src/lvgl/examples/widgets/led \
Core/Src/lvgl/examples/widgets/line \
Core/Src/lvgl/examples/widgets/list \
Core/Src/lvgl/examples/widgets/meter \
Core/Src/lvgl/examples/widgets/msgbox \
Core/Src/lvgl/examples/widgets/obj \
Core/Src/lvgl/examples/widgets/roller \
Core/Src/lvgl/examples/widgets/slider \
Core/Src/lvgl/examples/widgets/span \
Core/Src/lvgl/examples/widgets/spinbox \
Core/Src/lvgl/examples/widgets/spinner \
Core/Src/lvgl/examples/widgets/switch \
Core/Src/lvgl/examples/widgets/table \
Core/Src/lvgl/examples/widgets/tabview \
Core/Src/lvgl/examples/widgets/textarea \
Core/Src/lvgl/examples/widgets/tileview \
Core/Src/lvgl/examples/widgets/win \
Core/Src/lvgl/src/core \
Core/Src/lvgl/src/draw \
Core/Src/lvgl/src/extra/layouts/flex \
Core/Src/lvgl/src/extra/layouts/grid \
Core/Src/lvgl/src/extra \
Core/Src/lvgl/src/extra/others/snapshot \
Core/Src/lvgl/src/extra/themes/basic \
Core/Src/lvgl/src/extra/themes/default \
Core/Src/lvgl/src/extra/themes/mono \
Core/Src/lvgl/src/extra/widgets/animimg \
Core/Src/lvgl/src/extra/widgets/calendar \
Core/Src/lvgl/src/extra/widgets/chart \
Core/Src/lvgl/src/extra/widgets/colorwheel \
Core/Src/lvgl/src/extra/widgets/imgbtn \
Core/Src/lvgl/src/extra/widgets/keyboard \
Core/Src/lvgl/src/extra/widgets/led \
Core/Src/lvgl/src/extra/widgets/list \
Core/Src/lvgl/src/extra/widgets/meter \
Core/Src/lvgl/src/extra/widgets/msgbox \
Core/Src/lvgl/src/extra/widgets/span \
Core/Src/lvgl/src/extra/widgets/spinbox \
Core/Src/lvgl/src/extra/widgets/spinner \
Core/Src/lvgl/src/extra/widgets/tabview \
Core/Src/lvgl/src/extra/widgets/tileview \
Core/Src/lvgl/src/extra/widgets/win \
Core/Src/lvgl/src/font \
Core/Src/lvgl/src/gpu \
Core/Src/lvgl/src/gpu/sdl \
Core/Src/lvgl/src/hal \
Core/Src/lvgl/src/misc \
Core/Src/lvgl/src/widgets \
Core/Src/lvgl/tests/src \
Core/Src/lvgl/tests/src/test_cases \
Core/Src/lvgl/tests/src/test_fonts \
Core/Src/lvgl/tests/unity \
Core/Src \
Core/Src/tft \
Core/Src/touchpad \
Core/Startup \
Drivers/BSP/Components/adv7533 \
Drivers/BSP/Components/ft6x06 \
Drivers/BSP/Components/is42s32800j \
Drivers/BSP/Components/mt25tl01g \
Drivers/BSP/Components/otm8009a \
Drivers/BSP/Components/ov5640 \
Drivers/BSP/Components/ov9655 \
Drivers/BSP/Components/wm8994 \
Drivers/BSP/STM32H747I-Discovery \
Drivers/STM32H7xx_HAL_Driver \

